import os

CONSUMER_KEY = os.environ['TWITTER-API-KEY']
CONSUMER_SECRET = os.environ['TWITTER-API-KEY-SECRET']
ACCESS_TOKEN = os.environ['TWITTER-ACCESS-TOKEN']
ACCESS_TOKEN_SECRET = os.environ['TWITTER-ACCESS-TOKEN-SECRET']

EMAIL_PASSWORD = os.environ['EMAIL_PASSWORD']
